version: '3'
volumes:
  ? node_modules
services:
  web:
    image: douban-trailer/web
    links: 
      - db
    build:
      context: .
    command: 'yarn start'
    ports:
      - '3000:3000'
  dev:
    image: douban-trailer/dev
    links: 
      - db
    build:
      context: .
    # command: 'npm run dev'
    volumes:
      - .:/douban-trailer
      - node_modules:/douban-trailer/node_modules
    ports:
      - '3000:3000'
      - '9229:9229'
  db:
    image: mongo
    volumes:
      - "/data/db:/data/db"
    restart: always
